### ISSUE TITLE
Bad behaviour inside a replicator set @ 2.6.9

### ISSUE THREAD

**Issue by maxfahl** [lesaff/statamic-sections#4]
Trying to use this plugin with tabbed sections without success.

```
title: Block page
fields:

  title:
    type: title
    display: Title

  blocks:
    type: replicator
    sets:

      default_block:
        display: Standard
        fields:
          general_fields:
            display: General
            type: section
          format:
            display: Format
            type: select
            options:
              2-1-100: 2:1 100%
              1-1-100: 1:1 100%
              1-1-50: 1:1 50%
              1-2-50: 1:2 50%
            default: format-2-1-100
          top_text:
            display: Top Text
            type: redactor
            settings: Minor
          middle_text:
            display: Middle Text
            type: redactor
            settings: Minor
          bottom_text:
            display: Bottom Text
            validate: boolean
            type: redactor
            settings: Minor
          background_fields:
            display: Backgrounds
            type: section
          background_color:
            display: Bakground color
            type: text
          background_image:
            display: Bakground image
            type: assets
            container: main
            max_files: 1

      expand_block:
        display: Expand
        fields:
          col_1:
            display: Column 1
            type: redactor
            settings: Minor
          col_2:
            display: Column 2
            type: redactor
            settings: Minor
          col_3:
            display: Column 3
            validate: boolean
            type: redactor
            settings: Minor
          background_color:
            display: Bakground color
            type: text
          extra-v-padding:
            display: Extra vertical padding
            type: toggle
            default: false

      divider_block:
        display: Divider
        fields:
          padded:
            display: Padded
            type: toggle
            default: true
```

Results:

![screen shot 2017-10-24 at 09 09 59](https://user-images.githubusercontent.com/19852554/31929257-a09a7616-b89b-11e7-92c5-f85b258cb3ca.png)
