### ISSUE TITLE
Sections collapsing parent

### ISSUE THREAD

**Issue by KimKJDesigns** [lesaff/statamic-sections#6]
I've been using this for a few days now. It was perfect to pull all my fields into shape as I have a huge amount of flexibility in my fieldset. I hit a roadblock first using tabs, it completely messed the whole CP when accessing a page.

![image](https://user-images.githubusercontent.com/4345295/43446471-4e78dff2-94ec-11e8-9152-50e06654437c.png)

Changed to accordion (which was my preferred choice anyway) and bam, everything looked perfect.

![image](https://user-images.githubusercontent.com/4345295/43446585-9e2fbe1c-94ec-11e8-811c-368999e55765.png)

But I've just run into an issue. As you can see, I'm using a replicator inside a replicator. This still works, however, I have child grids as well. Inside these grids, I'm using a partial with a section. This partial is used in the grid parent as well, which is why when I click on the child sections, it collapses the parent and not the child.

![image](https://user-images.githubusercontent.com/4345295/43446918-7777fbd0-94ed-11e8-8592-62e1a4de610d.png)

This makes accessing the child sections impossible without disabling Sections :(. 

```
feature_1:
  display: Feature 1
  instructions: Background Video with content and features in the foreground.
  fields:
    section_settings:
      type: partial
      fieldset: theme/section_settings
    background_video:
      type: partial
      fieldset: theme/background_video
    content_copy:
      type: partial
      fieldset: theme/content_settings
    features:
      type: grid
      display: Features
      min_rows: 0
      max_rows: 3
      mode: stacked
      add_row: Add New Feature Item
      fields:
        content:
          type: partial
          fieldset: theme/content_settings
```
